#ifndef __IOCTLCODES_H_VERSION__
#define __IOCTLCODES_H_VERSION__ 100

#if _MSC_VER > 1000 
#pragma once  
#endif // _MSC_VER > 1000

#ifndef FILE_DEVICE_DEMENTIAKM
#define FILE_DEVICE_DEMENTIAKM 0x800
#endif

// Values defined for "Method"
// METHOD_BUFFERED
// METHOD_IN_DIRECT
// METHOD_OUT_DIRECT
// METHOD_NEITHER
// 
// Values defined for "Access"
// FILE_ANY_ACCESS
// FILE_READ_ACCESS
// FILE_WRITE_ACCESS

#define IOCTL_DEMENTIAKM_GET_SYMS \
		CTL_CODE(FILE_DEVICE_DEMENTIAKM, 0x800, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_DEMENTIAKM_STORE_SYMS \
		CTL_CODE(FILE_DEVICE_DEMENTIAKM, 0x801, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_DEMENTIAKM_STORE_FINISH_EVENT \
		CTL_CODE(FILE_DEVICE_DEMENTIAKM, 0x803, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_DEMENTIAKM_START_HIDING \
		CTL_CODE(FILE_DEVICE_DEMENTIAKM, 0x804, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_DEMENTIAKM_REMOVE_HOOKS \
		CTL_CODE(FILE_DEVICE_DEMENTIAKM, 0x805, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#endif